In [1]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import numpy as np
from numpy import argmax
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics 

In [5]:
iris = load_iris()
X = iris['data']
y = to_categorical(iris['target'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

model = Sequential()
model.add(Dense(1, input_dim=4, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 20)

Epoch 1/20
4/4 [==============================] - 1s 61ms/step - loss: 1.1013 - accuracy: 0.4262 - val_loss: 1.0179 - val_accuracy: 0.3667
Epoch 2/20
4/4 [==============================] - 0s 10ms/step - loss: 1.0653 - accuracy: 0.3683 - val_loss: 0.9909 - val_accuracy: 0.7333
Epoch 3/20
4/4 [==============================] - 0s 10ms/step - loss: 1.0315 - accuracy: 0.6115 - val_loss: 0.9699 - val_accuracy: 0.7333
Epoch 4/20
4/4 [==============================] - 0s 10ms/step - loss: 0.9840 - accuracy: 0.6417 - val_loss: 0.9538 - val_accuracy: 0.7333
Epoch 5/20
4/4 [==============================] - 0s 10ms/step - loss: 0.9816 - accuracy: 0.6440 - val_loss: 0.9389 - val_accuracy: 0.7333
Epoch 6/20
4/4 [==============================] - 0s 10ms/step - loss: 0.9479 - accuracy: 0.6804 - val_loss: 0.9265 - val_accuracy: 0.7333
Epoch 7/20
4/4 [==============================] - 0s 9ms/step - loss: 0.9344 - accuracy: 0.6525 - val_loss: 0.9141 - val_accuracy: 0.7333
Epoch 8/20
4/4 [============

In [6]:
results = model.evaluate(X_test, y_test)
print(f'Final test set loss: {results[0]}')
print(f'Final test set accuracy: {results[1]}')
model.summary()

1/1 [==============================] - 0s 11ms/step - loss: 0.7860 - accuracy: 0.7333
Final test set loss: 0.7860056757926941
Final test set accuracy: 0.7333333492279053
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 1)                 5         
_________________________________________________________________
dense_9 (Dense)              (None, 20)                40        
_________________________________________________________________
dense_10 (Dense)             (None, 20)                420       
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 63        
Total params: 528
Trainable params: 528
Non-trainable params: 0
_________________________________________________________________


In [22]:
prediction = model.predict(X_test)
num = 30
for i in range(num):
    if argmax(y_test[i]) != argmax(prediction[i]):
        print(f'For {i} index of test data the model was mistaken.')
        print(f'Actual type: {argmax(y_test[i])} Predicted type: {argmax(prediction[i])}')


For 13 index of test data the model was mistaken.
Actual type: 2 Predicted type: 1
For 27 index of test data the model was mistaken.
Actual type: 2 Predicted type: 1


In [23]:
print(confusion_matrix(np.argmax(y_test, axis=1), np.argmax(prediction, axis=1)))

[[12  0  0]
 [ 0  6  0]
 [ 0  2 10]]
